import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { checkBuildFreshness, checkExecutionContracts, checkPolicyRecords, checkTemporalEvidence } from "./executionAudit.js";
import { computeCurrentIdentity } from "../shared/projectIdentity.js";
import type { DirectDesignPlan, VerificationReport } from "../shared/artifacts.js";

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "dreative-execution-"));
  fs.mkdirSync(path.join(root, "src"), { recursive: true }); fs.mkdirSync(path.join(root, "public"), { recursive: true }); fs.mkdirSync(path.join(root, "dist"), { recursive: true });
  fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({ dependencies: { react: "^18.3.1", gsap: "^3.12.0" }, scripts: { build: "vite build" } }));
  fs.writeFileSync(path.join(root, "package-lock.json"), JSON.stringify({ packages: { "node_modules/gsap": { version: "3.12.0" } } }));
  fs.writeFileSync(path.join(root, "src", "Hero.tsx"), `import gsap from "gsap"; export function Hero(){ gsap.timeline(); return <section data-dreative-section="hero" data-dreative-motion="hero-motion">Hero</section> }`);
  fs.writeFileSync(path.join(root, "dist", "index.html"), "built");
  const plan = {
    version: 6, doctrineVersion: 6, tier: "award", configuration: { ambition: "award", execution: "lean", prototype: "skip", purpose: "project-delivery" },
    skills: ["ux", "mobile", "motion"], allSkillsExplicit: false,
    pages: [{ id: "home", name: "Home", skills: ["ux", "mobile", "motion"], sections: [{ id: "hero", name: "Hero", status: "shipped", skills: ["ux", "mobile", "motion"], assets: [] }] }],
    runtimeStack: [{ mechanism: "GSAP timeline", reason: "Coordinated structural chapter transformation", ownerIds: ["hero-motion"], requiredPackages: [{ name: "gsap", compatibleVersion: "^3.12.0", dependencySection: "dependencies" }], installCommand: "npm i gsap", packageManager: "npm", integrationFiles: ["src/Hero.tsx"], provider: "Hero", tickerOrScrollOwner: "gsap", fallback: "authored SVG state", installationStatus: "installed", importUseStatus: "used" }],
    runtimeBindings: [{ id: "hero-motion", kind: "motion", pageId: "home", sectionId: "hero", sourceFile: "src/Hero.tsx", component: "Hero", selector: "[data-dreative-motion=hero-motion]", mechanism: "GSAP timeline", dependencies: ["gsap"], assets: [], states: { start: "assembled", intermediate: "fan", end: "rail", fallback: "rail" }, observableProperties: ["transform"], evidenceIds: ["start", "mid", "end"] }],
    skillCoverage: ["ux", "mobile", "motion"].map((skill) => ({ skill, level: skill === "motion" ? "signature" : "universal", pageIds: ["home"], sectionIds: ["hero"], implementationFiles: ["src/Hero.tsx"], components: ["Hero"], contribution: `${skill} owns a substantive accessible authored contribution`, relatedOwnerIds: ["hero-motion"], evidenceIds: ["end"] })),
    foundation: { passed: true, sourceRevisionHash: "pending", dependencyEvidenceIds: ["end"], lifecycleOwner: "Hero", cleanup: "timeline killed on unmount", reducedMotion: "resolved state", contentBeforeEnhancement: "semantic section", firstCompositionEvidenceIds: ["start"], structuralChangeEvidenceIds: ["mid"], inputResponseEvidenceIds: ["mid"], mobileEvidenceIds: ["end"], representativeAssetPaths: [] },
    awardJourney: { firstViewportMomentId: "hero-motion", structuralMomentIds: ["hero-motion", "resolution"], inputInteractionId: "hero-motion", persistentSystemId: "rail", persistentSectionIds: ["hero", "close"], finalResolutionMomentId: "resolution", temporalArc: { setup: "hero assembles", anticipation: "fan resists", transformation: "fan becomes rail", rest: "rail pauses", handoff: "rail guides next", resolution: "rail closes mark" } },
    motionMoments: [
      { id: "hero-motion", class: "transformational", purpose: "First viewport composition develops into the journey rail", renderingMechanism: "GSAP timeline" },
      { id: "resolution", class: "structural", purpose: "Journey resolves into the closing mark", renderingMechanism: "GSAP timeline" },
    ], mediaTransformations: [],
  } as unknown as DirectDesignPlan;
  return { root, plan };
}

const messages = (root: string, plan: DirectDesignPlan) => checkExecutionContracts(root, plan).map((item) => item.message);

test("rejects Award plan claiming a runtime with only React installed", () => { const { root, plan } = fixture(); delete JSON.parse("{}").x; fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({ dependencies: { react: "^18" } })); assert.ok(messages(root, plan).some((x) => x.includes("gsap"))); });
test("rejects declared Three.js canvas with no three dependency", () => { const { root, plan } = fixture(); plan.runtimeBindings![0].dependencies = ["three"]; assert.ok(messages(root, plan).some((x) => x.includes("three"))); });
test("rejects installed dependency with no production import", () => { const { root, plan } = fixture(); fs.writeFileSync(path.join(root, "src", "Hero.tsx"), `export function Hero(){return <section data-dreative-motion="hero-motion"/>}`); assert.ok(messages(root, plan).some((x) => x.includes("no production import"))); });
test("rejects implementation file that does not emit its mounted selector", () => { const { root, plan } = fixture(); fs.writeFileSync(path.join(root, "src", "Hero.tsx"), `import gsap from "gsap"; export function Hero(){gsap.timeline();return <section/>}`); assert.ok(messages(root, plan).some((x) => x.includes("selector"))); });
test("rejects planned section missing from reconciliation", () => { const { root, plan } = fixture(); const verify = { reconciliation: { planned: [], observed: [], missing: ["hero-motion"], substituted: [], extra: [] } } as any; assert.ok(checkExecutionContracts(root, plan, verify).some((x) => x.check === "runtime-reconciliation")); });
test("rejects planned drag replaced by unapproved hover substitution", () => { const { root, plan } = fixture(); const verify = { reconciliation: { planned: ["hero-motion"], observed: ["hover"], missing: [], substituted: [{ plannedId: "hero-motion", observedId: "hover", approved: false, reason: "easier" }], extra: [] } } as any; assert.ok(checkExecutionContracts(root, plan, verify).some((x) => x.message.includes("silently substituted"))); });
test("rejects quote reel replaced by static columns", () => { const { root, plan } = fixture(); plan.runtimeBindings![0].id = "quote-reel"; const verify = { reconciliation: { planned: ["quote-reel"], observed: ["static-columns"], missing: [], substituted: [{ plannedId: "quote-reel", observedId: "static-columns", approved: false, reason: "" }], extra: [] } } as any; assert.ok(checkExecutionContracts(root, plan, verify).some((x) => x.message.includes("silently"))); });
test("rejects absent sticky runtime owner", () => { const { root, plan } = fixture(); plan.runtimeStack![0].ownerIds = ["sticky-journey"]; assert.ok(messages(root, plan).some((x) => x.includes("unknown owner"))); });
test("rejects missing generated asset", () => { const { root, plan } = fixture(); plan.runtimeBindings![0].assets = ["public/generated.webp"]; assert.ok(messages(root, plan).some((x) => x.includes("missing or empty"))); });
test("rejects static fallback without approved reconciliation", () => { const { root, plan } = fixture(); const verify = { reconciliation: { planned: ["hero-motion"], observed: ["static"], missing: [], substituted: [{ plannedId: "hero-motion", observedId: "static", approved: false, reason: "tool failed" }], extra: [] } } as any; assert.ok(checkExecutionContracts(root, plan, verify).some((x) => x.message.includes("silently"))); });
test("rejects explicit all when selected skills were pruned", () => { const { root, plan } = fixture(); plan.allSkillsExplicit = true; assert.ok(messages(root, plan).some((x) => x.includes("silently pruned"))); });
test("rejects selected skill with no material owner", () => { const { root, plan } = fixture(); plan.skillCoverage = plan.skillCoverage!.filter((x) => x.skill !== "motion"); assert.ok(messages(root, plan).some((x) => x.includes("motion has no substantive owner"))); });
test("rejects incompatible planned runtime major", () => { const { root, plan } = fixture(); plan.runtimeStack![0].requiredPackages[0].compatibleVersion = "^4"; assert.ok(messages(root, plan).some((x) => x.includes("incompatible"))); });
test("rejects tiny pointer parallax as Award signature", () => { const { root, plan } = fixture(); (plan.motionMoments![0] as any).purpose = "tiny pointer parallax"; assert.ok(messages(root, plan).some((x) => x.includes("micro-motion"))); });
test("rejects slow decorative rotation as temporal choreography", () => { const { root, plan } = fixture(); (plan.motionMoments![0] as any).renderingMechanism = "slow infinite rotation"; assert.ok(messages(root, plan).some((x) => x.includes("micro-motion"))); });
test("rejects offscreen auto-running CSS motion", () => { const { root, plan } = fixture(); fs.writeFileSync(path.join(root, "src", "Hero.tsx"), `import gsap from "gsap"; export function Hero(){gsap.timeline();return <section data-dreative-motion="hero-motion" style={{animation:"go 1s"}}/>}`); assert.ok(messages(root, plan).some((x) => x.includes("offscreen"))); });
test("rejects a source asset present but never loaded", () => { const { root, plan } = fixture(); fs.writeFileSync(path.join(root, "public", "asset.png"), "asset"); plan.runtimeBindings![0].assets = ["public/asset.png"]; assert.ok(messages(root, plan).some((x) => x.includes("never loaded"))); });

function temporalFixture() {
  const { root, plan } = fixture();
  const evidence = ["initial", "mid-transition", "final"].map((timelineState, index) => ({ id: `e${index}`, criterion: "motion", status: "pass", evidence: "browser capture", kind: "motion", motionMomentId: "hero-motion", timelineState, proof: { timestamp: new Date().toISOString(), captureSource: "browser", captureManifestPath: ".dreative/capture.json", observedProperties: [{ property: "x", expected: `${index}`, observed: `${index}` }] } }));
  return { root, plan, report: { version: 4, generatedAt: new Date().toISOString(), evidence } as any as VerificationReport };
}
test("rejects fake controlled-progress JSON without browser grounding", () => { const { root, plan, report } = temporalFixture(); report.evidence[0].proof.captureSource = undefined; assert.ok(checkTemporalEvidence(root, plan, report).some((x) => x.message.includes("browser-grounded"))); });
test("rejects reused screenshots with different timeline labels", () => { const { root, plan, report } = temporalFixture(); report.evidence.forEach((x) => x.proof.artifactHash = "same"); assert.ok(checkTemporalEvidence(root, plan, report).some((x) => x.message.includes("reused frame"))); });
test("rejects identical observed values across temporal states", () => { const { root, plan, report } = temporalFixture(); report.evidence.forEach((x) => x.proof.observedProperties = [{ property: "x", expected: "1", observed: "1" }]); assert.ok(checkTemporalEvidence(root, plan, report).some((x) => x.message.includes("distinct"))); });
test("rejects critic screenshots-only condition through missing temporal evidence", () => { const { root, plan } = fixture(); const report = { version: 4, evidence: [] } as any; assert.ok(checkTemporalEvidence(root, plan, report).some((x) => x.message.includes("grounded start"))); });

test("rejects verification from an older source hash", () => { const { root } = fixture(); const now = new Date().toISOString(); const identity = computeCurrentIdentity(root, { runId: "r", dreativeVersion: "0.6.0", schemaVersion: 4, framework: "vite", packageManager: "npm", buildCommand: "npm run build", serverCommand: "npm run preview", testedOrigin: "http://localhost:4173", testedUrl: "http://localhost:4173/", serverStartedAt: now, verificationStartedAt: now, verificationFinishedAt: now }); fs.appendFileSync(path.join(root, "src", "Hero.tsx"), "change"); assert.ok(checkBuildFreshness(root, { version: 4, generatedAt: now, runId: "r", buildIdentity: identity, evidence: [] } as any).length); });
test("rejects verification after lockfile modification", () => { const { root } = fixture(); const now = new Date().toISOString(); const identity = computeCurrentIdentity(root, { runId: "r", dreativeVersion: "0.6.0", schemaVersion: 4, framework: "vite", packageManager: "npm", buildCommand: "npm run build", serverCommand: "npm run preview", testedOrigin: "http://localhost:4173", testedUrl: "http://localhost:4173/", serverStartedAt: now, verificationStartedAt: now, verificationFinishedAt: now }); fs.appendFileSync(path.join(root, "package-lock.json"), " "); assert.ok(checkBuildFreshness(root, { version: 4, generatedAt: now, runId: "r", buildIdentity: identity, evidence: [] } as any).some((x) => x.message.includes("lockfileHash"))); });
test("rejects verification after production build modification", () => { const { root } = fixture(); const now = new Date().toISOString(); const identity = computeCurrentIdentity(root, { runId: "r", dreativeVersion: "0.6.0", schemaVersion: 4, framework: "vite", packageManager: "npm", buildCommand: "npm run build", serverCommand: "npm run preview", testedOrigin: "http://localhost:4173", testedUrl: "http://localhost:4173/", serverStartedAt: now, verificationStartedAt: now, verificationFinishedAt: now }); fs.appendFileSync(path.join(root, "dist", "index.html"), "change"); assert.ok(checkBuildFreshness(root, { version: 4, generatedAt: now, runId: "r", buildIdentity: identity, evidence: [] } as any).some((x) => x.message.includes("productionBuildHash"))); });
test("accepts current dirty-worktree identity by hashing actual files", () => { const { root } = fixture(); const now = new Date().toISOString(); const identity = computeCurrentIdentity(root, { runId: "r", dreativeVersion: "0.6.0", schemaVersion: 4, framework: "vite", packageManager: "npm", buildCommand: "npm run build", serverCommand: "npm run preview", testedOrigin: "http://localhost:4173", testedUrl: "http://localhost:4173/", serverStartedAt: now, verificationStartedAt: now, verificationFinishedAt: now }); assert.deepEqual(checkBuildFreshness(root, { version: 4, generatedAt: now, runId: "r", buildIdentity: identity, evidence: [] } as any), []); });

test("Full Audit rejects missing certification", () => { const { root, plan } = fixture(); plan.configuration!.execution = "full-audit"; assert.ok(checkPolicyRecords(root, plan).some((x) => x.check === "certification")); });
test("Dogfood rejects missing behaviour analysis", () => { const { root, plan } = fixture(); plan.configuration!.purpose = "dreative-dogfood"; assert.ok(checkPolicyRecords(root, plan).some((x) => x.check === "behaviour-analysis")); });
test("certification cannot claim completion after audit failure", () => { const { root, plan } = fixture(); plan.configuration!.execution = "full-audit"; fs.mkdirSync(path.join(root, ".dreative")); fs.writeFileSync(path.join(root, ".dreative", "certification.json"), JSON.stringify({ version: 1, auditResult: "fail", verificationResult: "pass", tierSatisfied: true, completionStatus: "complete", commands: [] })); assert.ok(checkPolicyRecords(root, plan).some((x) => x.message.includes("honestly satisfied"))); });

for (const [name, mechanism] of [["CSS/SVG structural Award", "CSS SVG structural mask"], ["Motion gesture/layout architecture", "motion/react layout gesture"], ["GSAP pinned narrative", "GSAP ScrollTrigger pinned"], ["Three.js persistent stage", "three WebGL persistent stage"], ["frame-sequence media system", "canvas frame sequence"]]) {
  test(`passing fixture: ${name}`, () => { const { root, plan } = fixture(); plan.runtimeBindings![0].mechanism = mechanism; assert.equal(messages(root, plan).filter((x) => x.includes("decorative micro-motion")).length, 0); });
}
